"use client";

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';

const FlightOfferBanner = () => {
  return (
    <section className="max-w-7xl mx-auto px-4 py-6 md:py-8">
      <Link href="/offers" className="block group">

        {/*
          ✅ Single container — aspect ratio handles both mobile and desktop
          aspect-[16/9] on mobile, fixed h-80 on md+
          No competing fixed heights fighting each other
        */}
        <div className="relative w-full aspect-[26/9] md:aspect-auto md:h-80 rounded-[1rem] overflow-hidden">

          {/*
            ✅ Single Image — fill on all breakpoints
            No duplicate requests, no hydration mismatch
            ✅ loading="lazy" — this component is dynamic-imported, not LCP
            ✅ sizes — proper responsive srcset generated by Next.js
          */}
          <Image
            src="/flight_eammu_offer.webp"
            alt="Special flight offers from Bangladesh and Dubai — book now"
            fill
            loading="lazy"
            className="object-cover transition-transform duration-700 group-hover:scale-105"
            sizes="(max-width: 768px) 100vw, (max-width: 1280px) 100vw, 1280px"
            quality={75}
          />

          {/* Gradient overlay */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-70 group-hover:opacity-40 transition-opacity pointer-events-none" />

          {/*
            ✅ Button — CSS hover/active replaces whileHover/whileTap
            active:scale-95 = whileTap, hover:scale-105 = whileHover
          */}
          <div className="absolute bottom-3 left-4 md:bottom-5 md:left-8 hidden md:flex">
            <div className="bg-[#005a31] text-white px-5 py-2 md:px-7 md:py-3 rounded-lg md:rounded-xl font-black uppercase tracking-widest shadow-2xl flex items-center gap-2 transition-all duration-300 text-[10px] md:text-sm
                            group-hover:bg-[#ffcc00] group-hover:text-[#005a31]
                            hover:scale-105 active:scale-95">
              Book Now
              <span className="text-sm md:text-md" aria-hidden="true">→</span>
            </div>
          </div>

        </div>
      </Link>
    </section>
  );
};

export default FlightOfferBanner;