/**
 * ✅ SHARED REJECTION DATA
 * File: app/lib/rejectionData.js
 */

export const REJECTION_RULES = {
  canada: {
    name: "Canada",
    flag: "🇨🇦",
    embassyUrl: "https://www.canada.ca/en/immigration-refugees-citizenship.html",
    types: {
      tourist: {
        rate: 38,
        risk: "High",
        label: "Temporary Resident Visa (TRV)",
        trend: "up",
        trendNote: "Refusal rate up 6% since 2023 for South Asian applicants",
        byNationality: { "Bangladesh": 44, "India": 32, "Pakistan": 41, "Nigeria": 52, "Average": 38 },
        topReasons: [
          { pct: 68, reason: "Insufficient financial documentation", detail: "Bank balance below $10,000 CAD equivalent or funds not held consistently for 6+ months. Lump-sum deposits raise red flags." },
          { pct: 54, reason: "Weak ties to home country", detail: "No stable employment letter, no property ownership, no dependents. Officers must believe you will return home." },
          { pct: 41, reason: "Inadequate travel history", detail: "First-time applicants or those with no prior developed-country visa. No travel record increases perceived overstay risk." },
          { pct: 33, reason: "Vague or unconvincing travel purpose", detail: "No detailed itinerary, no hotel bookings, or purpose of visit unclear. 'Sightseeing' without specifics is not convincing." },
          { pct: 27, reason: "Missing or inconsistent documents", detail: "Gaps in employment, unexplained income sources, or discrepancies between stated purpose and submitted evidence." },
          { pct: 19, reason: "Prior refusal not declared", detail: "Misrepresentation — even accidental — results in 5-year or permanent ban from Canadian immigration." },
        ],
        fixes: [
          { title: "Show 6 months of stable bank history", icon: "💰", impact: "High", desc: "Maintain at least $10,000–$15,000 CAD equivalent consistently. Avoid large one-time deposits. Officers check transaction patterns, not just balance." },
          { title: "Get a strong employer letter", icon: "📄", impact: "High", desc: "Must be on company letterhead, signed by HR/management, state your position, salary, approved leave dates, and confirmation you will return to your role." },
          { title: "Write a detailed cover letter", icon: "✍️", impact: "High", desc: "Explain exactly why you want to visit Canada, what you will do day-by-day, and why you will return. Address any weaknesses in your profile proactively." },
          { title: "Show proof of property or assets", icon: "🏠", impact: "Medium", desc: "Land deed, car ownership, business registration — anything that proves you have financial and personal stakes in your home country." },
          { title: "Book refundable hotels and flights", icon: "✈️", impact: "Medium", desc: "Flexible bookings show commitment without risk. Include a day-by-day itinerary referencing real Canadian attractions." },
          { title: "Always declare prior refusals", icon: "📋", impact: "Critical", desc: "Hiding past refusals is misrepresentation — automatic rejection plus potential ban. Declare everything and explain the circumstances." },
        ],
        documents: [
          "Valid passport (6+ months validity beyond intended stay)",
          "Completed IMM 5257 application form",
          "2 passport-sized photographs (per IRCC specs)",
          "6 months of bank statements (all accounts)",
          "Employer letter with salary, position, approved leave",
          "Income tax returns (last 2 years)",
          "Property documents / asset proof",
          "Invitation letter (if visiting family/friends)",
          "Hotel bookings and flight itinerary",
          "Detailed cover letter explaining purpose of visit",
          "Travel insurance (recommended, not mandatory)",
          "Proof of biometrics (if previously enrolled)",
        ],
        stats: {
          approvalTime: "15–21 business days",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Apply at least 10–12 weeks before your travel date — peak season (Jun–Aug) adds 2–3 weeks",
          "Use IRCC's online portal — paper applications are slower and harder to track",
          "If refused, wait at least 3 months before reapplying and address every noted concern",
          "A prior US, UK, or Schengen visa significantly improves your Canadian TRV chances",
          "GCMS notes (access to your file) can reveal the exact refusal reason — request them after refusal",
        ],
        successStories: "Applicants who include a strong cover letter addressing financial ties and travel purpose have a 40% higher approval rate according to IRCC processing data.",
      },
      student: {
        rate: 18,
        risk: "Medium",
        label: "Canadian Study Permit",
        trend: "stable",
        trendNote: "Study permit refusals stable in 2024 after SDS stream changes",
        byNationality: { "Bangladesh": 22, "India": 16, "Pakistan": 24, "Nigeria": 31, "Average": 18 },
        topReasons: [
          { pct: 58, reason: "Insufficient proof of funds", detail: "Must show tuition + $10,000 CAD living expenses for first year. Funds must be accessible and verifiable." },
          { pct: 44, reason: "Weak study plan / purpose statement", detail: "Why Canada? Why this program? Why now? Officers must be convinced you have genuine academic goals." },
          { pct: 36, reason: "Doubts about returning home post-study", detail: "No ties to home country, no clear career plan, or applying to a program unrelated to current career." },
          { pct: 22, reason: "Acceptance letter issues", detail: "Conditional acceptance, low-ranked institution, or program inconsistent with academic background." },
          { pct: 18, reason: "Language proficiency gaps", detail: "IELTS/TOEFL scores not meeting the institution's requirements or below IRCC benchmarks." },
          { pct: 12, reason: "Prior study permit refusal", detail: "Multiple refusals significantly reduce credibility unless circumstances clearly changed." },
        ],
        fixes: [
          { title: "Write a compelling Statement of Purpose", icon: "📝", impact: "High", desc: "Explain why you chose this specific program, this specific Canadian institution, and how it connects directly to your career back home." },
          { title: "Show full financial proof", icon: "💰", impact: "High", desc: "Bank statements + GIC (Guaranteed Investment Certificate) via SDS stream. Sponsor letters must include their own income proof." },
          { title: "Demonstrate clear return intent", icon: "🏠", impact: "High", desc: "Career plan post-graduation in your home country. Job offer letters, family business, sector demand data." },
          { title: "Choose a DLI with strong track record", icon: "🎓", impact: "Medium", desc: "Designated Learning Institutions with high visa approval rates for your nationality. Avoid colleges with recent fraud issues." },
          { title: "Apply through SDS if eligible", icon: "⚡", impact: "High", desc: "Student Direct Stream (for eligible countries) offers faster processing and higher approval rates when all criteria met." },
          { title: "Address English proficiency clearly", icon: "📊", impact: "Medium", desc: "IELTS 6.0+ for most programs. Include your test report form in the application." },
        ],
        documents: [
          "Acceptance letter from Designated Learning Institution (DLI)",
          "Proof of financial support (bank statements, GIC, sponsor)",
          "Statement of Purpose / Study Plan",
          "Academic transcripts and certificates",
          "Language test results (IELTS/TOEFL)",
          "Passport (valid 6+ months beyond program end)",
          "Biometrics enrollment",
          "Provincial Attestation Letter (PAL) — now mandatory",
          "Quebec Acceptance Certificate (if studying in Quebec)",
        ],
        stats: {
          approvalTime: "8–12 weeks",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: false,
        },
        tips: [
          "Apply for the PAL (Provincial Attestation Letter) from your province before submitting to IRCC",
          "SDS applicants get faster decisions — if eligible, always use this stream",
          "A Canadian education consultant can significantly improve your application quality",
          "Apply as early as possible — October for January intake, March for September intake",
        ],
        successStories: "Study permit applicants who include a GIC and a well-structured study plan have approval rates of over 82% according to IRCC 2024 data.",
      },
      work: {
        rate: 22,
        risk: "Medium",
        label: "Canadian Work Permit",
        trend: "down",
        trendNote: "Work permit refusals decreasing as Express Entry draws increase",
        byNationality: { "Bangladesh": 28, "India": 18, "Pakistan": 30, "Nigeria": 35, "Average": 22 },
        topReasons: [
          { pct: 52, reason: "LMIA not obtained or invalid", detail: "Most work permits require a Labour Market Impact Assessment from the employer. Missing or expired LMIA is instant refusal." },
          { pct: 38, reason: "Qualifications don't match job offer", detail: "Educational credentials must match NOC code requirements. Unrecognized foreign degrees are a common issue." },
          { pct: 29, reason: "Employer compliance issues", detail: "Employer not registered, not paying minimum wage, or LMIA conditions not met." },
          { pct: 21, reason: "Insufficient funds to establish in Canada", detail: "Even with a job offer, officers want to see you can support yourself on arrival." },
          { pct: 15, reason: "Criminal or medical inadmissibility", detail: "Background checks and medical exams are required. Some conditions cause inadmissibility." },
        ],
        fixes: [
          { title: "Ensure LMIA is valid and complete", icon: "📋", impact: "Critical", desc: "Work with your employer to confirm the LMIA is current, matches your NOC code, and all conditions are documented." },
          { title: "Get credentials assessed (ECA)", icon: "🎓", impact: "High", desc: "Educational Credential Assessment from WES or other approved body confirms your degree equivalency in Canada." },
          { title: "Use LMIA-exempt pathways if possible", icon: "⚡", impact: "High", desc: "IEC, intra-company transfers, CUSMA workers — exempt streams have faster processing and higher approvals." },
          { title: "Prepare settlement funds proof", icon: "💰", impact: "Medium", desc: "Even with a job offer, show 3 months of living expenses in your bank account for the destination province." },
        ],
        documents: [
          "Valid job offer letter (detailed, signed)",
          "LMIA number (if required)",
          "Educational credentials and WES assessment",
          "Work experience documents",
          "Passport and travel history",
          "Police clearance certificate",
          "Medical exam results (if required)",
          "Proof of settlement funds",
        ],
        stats: {
          approvalTime: "2–27 weeks (varies by stream)",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: false,
        },
        tips: [
          "LMIA-exempt work permits (IEC, ICT) are significantly faster — explore if you qualify",
          "Express Entry Comprehensive Ranking System (CRS) score of 480+ gives strong chances",
          "Provincial Nominee Programs (PNPs) offer an alternative pathway with lower CRS requirements",
        ],
        successStories: "Applicants using LMIA-exempt pathways like the International Mobility Program have approval rates above 85%.",
      },
      transit: {
        rate: 12,
        risk: "Low",
        label: "Canada Transit Visa",
        trend: "stable",
        trendNote: "Transit visa requirements unchanged; processing fast at 6–24 hours",
        byNationality: { "Bangladesh": 15, "India": 8, "Pakistan": 14, "Nigeria": 18, "Average": 12 },
        topReasons: [
          { pct: 48, reason: "Applied too late", detail: "Transit visa must be approved before travel. Applications submitted within 48 hours of transit are routinely refused." },
          { pct: 35, reason: "Passport validity issues", detail: "Passport must be valid for the entire transit period plus 6 months." },
          { pct: 22, reason: "Layover longer than 24 hours", detail: "Extended layovers require a full TRV, not a transit visa." },
          { pct: 15, reason: "Missing onward ticket", detail: "Must show confirmed onward booking. Open-jaw itineraries without return confuse officers." },
        ],
        fixes: [
          { title: "Apply at least 2 weeks before transit", icon: "📅", impact: "High", desc: "Even though processing is fast, apply early. Weekend and holiday periods may slow decisions." },
          { title: "Show confirmed onward booking", icon: "✈️", impact: "High", desc: "Your complete itinerary — inbound flight, Canadian transit, outward flight — must be clear and consistent." },
          { title: "Keep layover under 24 hours", icon: "⏱️", impact: "Critical", desc: "Transit visa is for brief connections only. If your layover is longer, apply for a full TRV." },
        ],
        documents: [
          "Valid passport",
          "Confirmed inbound and outward flight tickets",
          "Destination country visa (if applicable)",
          "Transit visa application form",
        ],
        stats: {
          approvalTime: "6–24 hours",
          biometricsRequired: false,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: false,
        },
        tips: [
          "Apply at least 7–14 days before travel even though processing is fast",
          "Confirm with your airline whether transit visa is required for your specific route",
          "Transit visa holders must remain in the international transit zone",
        ],
        successStories: "Transit visas have the highest approval rate of any Canadian visa category when applied for in advance with complete documentation.",
      },
      business: {
        rate: 28,
        risk: "Medium",
        label: "Business TRV",
        trend: "stable",
        trendNote: "Business visa refusals similar to tourist TRV, slightly lower",
        byNationality: { "Bangladesh": 34, "India": 24, "Pakistan": 38, "Nigeria": 44, "Average": 28 },
        topReasons: [
          { pct: 62, reason: "Weak business purpose evidence", detail: "No invitation letter from Canadian company, no conference registration, or vague description of business activities." },
          { pct: 45, reason: "Insufficient financial proof", detail: "Business trip expenses must be clearly funded. Personal or company bank statements required." },
          { pct: 33, reason: "No proof of established business", detail: "Trade license, company registration, tax returns confirming legitimate business activity." },
          { pct: 24, reason: "Ties to home country not established", detail: "Officers must believe you will return to run your business." },
        ],
        fixes: [
          { title: "Get an invitation from Canadian partner", icon: "📨", impact: "High", desc: "Invitation letter on Canadian company letterhead, with meeting dates, purpose, and contact details." },
          { title: "Show company financials", icon: "📊", impact: "High", desc: "Company bank statements, trade license, tax returns — prove your business is real and active." },
          { title: "Include conference or event registration", icon: "🎫", impact: "Medium", desc: "Registration for trade shows, conferences, or B2B meetings significantly strengthens purpose." },
        ],
        documents: [
          "Business invitation letter from Canadian company",
          "Trade license and company registration",
          "Company bank statements (6 months)",
          "Personal bank statements",
          "Conference/event registration (if applicable)",
          "Business card and company profile",
          "Employer letter (for employees attending on behalf of company)",
        ],
        stats: {
          approvalTime: "15–21 business days",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Business TRV uses the same form as tourist TRV — the difference is in the supporting documents",
          "A prior Canadian TRV approval history greatly helps business visa applications",
        ],
        successStories: "Business visitors with formal Canadian company invitations and strong financial profiles achieve approval rates of 72%.",
      },
      family: {
        rate: 33,
        risk: "High",
        label: "Family Sponsorship / Super Visa",
        trend: "up",
        trendNote: "Family visa refusals increasing due to stricter financial requirements",
        byNationality: { "Bangladesh": 38, "India": 28, "Pakistan": 42, "Nigeria": 45, "Average": 33 },
        topReasons: [
          { pct: 65, reason: "Sponsor financial requirements not met", detail: "Canadian sponsor must meet LICO (Low Income Cut-Off) thresholds. Falling below means automatic refusal." },
          { pct: 48, reason: "Relationship not sufficiently proven", detail: "Insufficient evidence of genuine relationship — no communication history, no photos, inconsistent statements." },
          { pct: 36, reason: "Applicant's ties to home country weak", detail: "Officers must believe the visiting family member will return home after the visit." },
          { pct: 28, reason: "Super Visa insurance not meeting requirements", detail: "Medical insurance must be from a Canadian insurer, $100,000 minimum, 1 year coverage." },
        ],
        fixes: [
          { title: "Verify sponsor meets LICO threshold", icon: "💰", impact: "Critical", desc: "Sponsor must show income at least 30% above LICO for their household size. NOA (Notice of Assessment) from CRA required." },
          { title: "Build relationship evidence", icon: "📸", impact: "High", desc: "Photos together, WhatsApp/email history, video call logs, money transfer records. The more documented, the better." },
          { title: "Get proper Super Visa insurance", icon: "🛡️", impact: "Critical", desc: "Must be from a Canadian insurance company (not foreign), $100,000+ coverage, starting from arrival date." },
          { title: "Show applicant's home ties", icon: "🏠", impact: "High", desc: "Property, employment, own children at home, bank accounts — evidence they have reason to return." },
        ],
        documents: [
          "Sponsor's NOA (Notice of Assessment) from CRA",
          "Sponsor's employment letter and pay stubs",
          "Proof of relationship (birth certificate, marriage certificate)",
          "Photographs and communication history",
          "Super Visa medical insurance from Canadian insurer",
          "Applicant's bank statements and property documents",
          "Statutory declaration of support from sponsor",
        ],
        stats: {
          approvalTime: "8–12 weeks",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Super Visa allows stays of up to 5 years at a time — much better than regular TRV for parents/grandparents",
          "If sponsor recently became PR, wait 12 months before sponsoring to show stable income",
        ],
        successStories: "Super Visa applications with proper LICO evidence and Canadian insurance have an approval rate of approximately 68%.",
      },
    },
  },
  "united-states": {
    name: "United States",
    flag: "🇺🇸",
    embassyUrl: "https://travel.state.gov/content/travel/en/us-visas.html",
    types: {
      tourist: {
        rate: 42,
        risk: "High",
        label: "B1/B2 Tourist/Business Visa",
        trend: "up",
        trendNote: "B2 refusals for South Asian applicants increased 8% in 2024",
        byNationality: { "Bangladesh": 48, "India": 35, "Pakistan": 52, "Nigeria": 62, "Average": 42 },
        topReasons: [
          { pct: 71, reason: "Section 214(b) — Immigrant intent presumed", detail: "US law presumes all B-visa applicants intend to immigrate. You must overcome this by proving strong ties to your home country." },
          { pct: 55, reason: "Insufficient ties to home country", detail: "No stable employment, no family dependents, no property or business. Officers need multiple reasons you'll return." },
          { pct: 44, reason: "Poor financial standing", detail: "Cannot show ability to fund the trip without working illegally in the US. Consistent savings matter more than high balance." },
          { pct: 32, reason: "Prior visa overstay or violation", detail: "Any overstay in the US or other countries is a serious red flag. Prior 221(g) or refusal also increases scrutiny." },
          { pct: 25, reason: "Interview performance", detail: "Short, unclear, or inconsistent answers at the consular interview. Officers decide in 2–3 minutes based on your interview." },
          { pct: 18, reason: "Travel to restricted countries", detail: "Recent travel to countries under US sanctions or security concerns can trigger 221(g) administrative processing." },
        ],
        fixes: [
          { title: "Build strong employment ties", icon: "💼", impact: "Critical", desc: "A government or established private sector job with confirmed return date is the single strongest tie. Include promotion history, seniority, and pension/EPF contributions." },
          { title: "Prepare for the 214(b) presumption", icon: "🛡️", impact: "Critical", desc: "Every answer must reinforce why you will return. Practice concise, confident answers about your job, family, property, and future plans." },
          { title: "Show 12 months of bank activity", icon: "💰", impact: "High", desc: "Active account with regular salary deposits. Consular officers look for organic savings behaviour, not one-time large transfers." },
          { title: "Dress professionally, speak confidently", icon: "👔", impact: "High", desc: "US consular interviews are 2–3 minutes long. First impressions matter enormously. Speak in English if confident." },
          { title: "Never mention immigration intent", icon: "🚫", impact: "Critical", desc: "Any hint of wanting to stay permanently in the US triggers automatic 214(b) refusal. Focus on temporary purpose and return plans." },
          { title: "Apply with prior US visa history", icon: "✈️", impact: "High", desc: "Prior US visa holders with no violations have dramatically higher approval rates. A clean US entry/exit history is gold." },
        ],
        documents: [
          "DS-160 completed online",
          "Valid passport (6+ months validity)",
          "Visa application fee payment receipt (MRV fee)",
          "Interview appointment confirmation",
          "Photograph (per US visa specs)",
          "Employment letter with salary, position, approved leave",
          "Bank statements (12 months)",
          "Income tax returns (2–3 years)",
          "Property documents",
          "US sponsor letter (if applicable)",
          "Hotel and flight itinerary",
        ],
        stats: {
          approvalTime: "Interview + 3–5 business days",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: false,
        },
        tips: [
          "Schedule your interview as early as possible — Dhaka embassy slots book 60–90 days ahead",
          "If refused under 214(b), you can reapply immediately but circumstances must have changed",
          "221(g) administrative processing has no fixed timeline — apply at least 6 months before travel",
          "Prior UK, Canada, or Schengen visa significantly helps US B2 approval",
          "Bring originals of all documents — never only photocopies",
        ],
        successStories: "Applicants with stable government jobs, property ownership, and family dependents at home achieve US B2 approval rates of 58–65%.",
      },
      student: {
        rate: 15,
        risk: "Low",
        label: "F-1 Student Visa",
        trend: "stable",
        trendNote: "F-1 approvals stable; STEM students from all nationalities approved at high rates",
        byNationality: { "Bangladesh": 18, "India": 12, "Pakistan": 20, "Nigeria": 25, "Average": 15 },
        topReasons: [
          { pct: 55, reason: "Insufficient financial proof", detail: "Must show full tuition + living expenses without need for unauthorized work. Sponsorship documents must be comprehensive." },
          { pct: 40, reason: "Weak ties to home country / immigrant intent", detail: "F-1 still requires showing non-immigrant intent. Career plan back home is essential." },
          { pct: 30, reason: "Interview not convincing", detail: "Unclear academic goals, inability to explain the program, or weak English proficiency." },
          { pct: 22, reason: "I-20 issues", detail: "Expired, incorrect, or conditionally issued I-20. Must be from a SEVP-certified institution." },
        ],
        fixes: [
          { title: "Show full financial coverage", icon: "💰", impact: "High", desc: "Bank statements or sponsor documentation must cover 100% of tuition + $1,500/month living costs for the entire program duration." },
          { title: "Know your program inside out", icon: "🎓", impact: "High", desc: "Be ready to explain why you chose this specific university, this specific major, and how it connects to your career goals back home." },
          { title: "Have a clear post-graduation plan", icon: "🎯", impact: "High", desc: "Describe a specific job role or business venture in your home country that requires this US education." },
          { title: "Ensure I-20 is current and correct", icon: "📋", impact: "Critical", desc: "Check all details — program start date, SEVIS ID, financial requirements. Any error on the I-20 leads to refusal." },
        ],
        documents: [
          "Form I-20 from SEVP-certified institution",
          "DS-160 completed online",
          "SEVIS fee payment receipt (I-901)",
          "MRV fee payment receipt",
          "Academic transcripts and diplomas",
          "TOEFL/IELTS/GRE/GMAT scores",
          "Financial evidence (full program cost coverage)",
          "Sponsor's financial documents (if sponsored)",
          "Ties to home country evidence",
        ],
        stats: {
          approvalTime: "Interview + 2–3 business days",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: false,
        },
        tips: [
          "Apply at least 120 days before program start — earliest entry is 30 days before",
          "Top-ranked universities have higher visa approval rates — the institution matters",
          "STEM OPT extension (3 years) is a strong incentive that officers know about",
        ],
        successStories: "F-1 students with full financial proof, strong academic records, and clear career plans achieve approval rates of 85%+.",
      },
      work: {
        rate: 10,
        risk: "Low",
        label: "H-1B / Work Visa",
        trend: "stable",
        trendNote: "H-1B cap lottery continues; approval rate high for selected petitions",
        byNationality: { "Bangladesh": 12, "India": 9, "Pakistan": 14, "Nigeria": 16, "Average": 10 },
        topReasons: [
          { pct: 45, reason: "Specialty occupation not proven", detail: "Role must require a specific bachelor's degree. Generic job descriptions don't qualify." },
          { pct: 30, reason: "Employer RFE not responded properly", detail: "USCIS issues RFEs for ambiguous petitions. Poor responses lead to denial." },
          { pct: 20, reason: "Wages below prevailing wage", detail: "Employer must pay at least the prevailing wage for the occupation and location." },
        ],
        fixes: [
          { title: "Ensure role clearly qualifies as specialty occupation", icon: "💼", impact: "Critical", desc: "Detailed job description referencing specific degree requirements. HR letters explaining why the role needs specialized education." },
          { title: "Respond thoroughly to any RFE", icon: "📋", impact: "High", desc: "Work with an immigration attorney to respond to USCIS RFEs. Missing the deadline or submitting weak evidence leads to denial." },
        ],
        documents: [
          "I-129 petition from employer",
          "LCA (Labor Condition Application)",
          "Degree certificate and transcripts",
          "Employment offer letter",
          "Prevailing wage determination",
        ],
        stats: {
          approvalTime: "3–6 months (regular), 15 days (premium processing)",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: true,
        },
        tips: [
          "H-1B cap is subject to lottery — apply in April for October start",
          "Cap-exempt employers (universities, nonprofits) offer H-1B without lottery",
        ],
        successStories: "H-1B petitions with detailed specialty occupation evidence and top-tier employer support have 90%+ approval rates.",
      },
      transit: {
        rate: 20,
        risk: "Medium",
        label: "C-1 Transit Visa",
        trend: "stable",
        trendNote: "C-1 transit required when transiting US airports without valid US visa",
        byNationality: { "Bangladesh": 24, "India": 15, "Pakistan": 26, "Nigeria": 32, "Average": 20 },
        topReasons: [
          { pct: 55, reason: "Immigrant intent", detail: "Even transit visas require showing non-immigrant intent under 214(b)." },
          { pct: 40, reason: "Onward itinerary not confirmed", detail: "Must show confirmed onward flight booking beyond the US." },
          { pct: 28, reason: "Destination country visa issues", detail: "If destination country visa is missing or expired, transit visa will be refused." },
        ],
        fixes: [
          { title: "Show complete transit itinerary", icon: "✈️", impact: "High", desc: "Inbound flight, US connection, outbound flight — all confirmed bookings. Layover must be under 24 hours." },
          { title: "Bring destination country visa", icon: "📋", impact: "Critical", desc: "Your valid visa for the destination country must be current and valid for entry." },
        ],
        documents: ["DS-160", "Confirmed transit itinerary", "Onward destination visa", "Passport", "MRV fee payment"],
        stats: {
          approvalTime: "Interview + 3–5 days",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: false,
        },
        tips: [
          "C-1 interview required in person at US embassy",
          "Apply at least 4–6 weeks before travel",
        ],
        successStories: "Transit visa applicants with confirmed itineraries and valid destination visas achieve 80%+ approval rates.",
      },
      business: {
        rate: 35,
        risk: "High",
        label: "B1 Business Visa",
        trend: "stable",
        trendNote: "B1 combined with B2 in same visa (B1/B2) — business purpose must be clearly documented",
        byNationality: { "Bangladesh": 42, "India": 28, "Pakistan": 48, "Nigeria": 58, "Average": 35 },
        topReasons: [
          { pct: 65, reason: "Business purpose not convincing", detail: "US immigration law defines permitted B1 activities narrowly. Must not be gainful employment." },
          { pct: 48, reason: "Company ties not proven", detail: "No company registration, no employer letter, no evidence of business activity." },
          { pct: 35, reason: "214(b) immigrant intent", detail: "Same as tourist visa — strong home ties required." },
        ],
        fixes: [
          { title: "Define exact B1 permitted activities", icon: "📋", impact: "Critical", desc: "B1 allows: meetings, negotiations, conferences, short-term training. Not working for a US company or receiving US income." },
          { title: "Bring comprehensive company documents", icon: "📊", impact: "High", desc: "Company registration, bank statements, business profile, and invitation from US company." },
        ],
        documents: ["DS-160", "Company invitation from US partner", "Company registration and trade license", "Company bank statements", "Business profile", "Employment letter"],
        stats: {
          approvalTime: "Interview + 3–5 days",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: false,
        },
        tips: [
          "B1/B2 visa covers both tourist and business purposes — no need for separate visas",
          "Prior B1/B2 visa history with clean record dramatically increases approval",
        ],
        successStories: "B1 applicants with formal US company invitations and strong business profiles achieve 65% approval rates.",
      },
      family: {
        rate: 25,
        risk: "Medium",
        label: "K-1 / IR Family Visa",
        trend: "stable",
        trendNote: "IR1/CR1 immigrant visas for spouses have strict documentation requirements",
        byNationality: { "Bangladesh": 30, "India": 20, "Pakistan": 35, "Nigeria": 38, "Average": 25 },
        topReasons: [
          { pct: 58, reason: "Relationship not sufficiently documented", detail: "Genuine relationship must be proven through extensive documentation. Arranged marriage without evidence of ongoing communication is high risk." },
          { pct: 44, reason: "Sponsor does not meet income requirements", detail: "US Petitioner must earn 125% above federal poverty guidelines for household size." },
          { pct: 32, reason: "Fraud or misrepresentation concerns", detail: "Inconsistencies in statements, photos, or timelines raise fraud flags." },
        ],
        fixes: [
          { title: "Build extensive relationship documentation", icon: "📸", impact: "Critical", desc: "2+ years of photos together, call logs, travel records showing in-person meetings, money transfer records, correspondence." },
          { title: "Petitioner must prove income threshold", icon: "💰", impact: "High", desc: "I-864 Affidavit of Support requires tax returns and W-2s showing 125% of poverty guidelines for family size." },
        ],
        documents: ["I-130 petition", "I-864 Affidavit of Support", "Relationship evidence (photos, calls, meetings)", "Sponsor's tax returns", "Marriage/engagement certificate", "Medical examination (Form I-693)"],
        stats: {
          approvalTime: "12–36 months (immigrant visa)",
          biometricsRequired: true,
          interviewRequired: true,
          onlineApply: false,
          appealAvailable: true,
        },
        tips: [
          "K-1 fiancé visa allows entry to the US before marriage — faster than spousal visa",
          "Once approved, immigrant visa holders get permanent resident status — not temporary",
        ],
        successStories: "Family visa applications with comprehensive relationship documentation and petitioner income above threshold achieve 75%+ approval.",
      },
    },
  },
  "united-kingdom": {
    name: "United Kingdom",
    flag: "🇬🇧",
    embassyUrl: "https://www.gov.uk/apply-uk-visa",
    types: {
      tourist: {
        rate: 29,
        risk: "Medium",
        label: "UK Standard Visitor Visa",
        trend: "stable",
        trendNote: "UK visitor visa refusals stable post-Brexit eVisa transition",
        byNationality: { "Bangladesh": 35, "India": 22, "Pakistan": 38, "Nigeria": 44, "Average": 29 },
        topReasons: [
          { pct: 64, reason: "Insufficient financial evidence", detail: "Home Office requires clear evidence you can fund the trip without needing to work. Savings must be genuinely held — not borrowed." },
          { pct: 51, reason: "Ties to home country not compelling", detail: "UK ECOs (Entry Clearance Officers) assess whether you are likely to overstay. Employment, property, and family ties must be documented." },
          { pct: 38, reason: "Accommodation not confirmed", detail: "No hotel bookings or host invitation letter with address and relationship explanation." },
          { pct: 29, reason: "Travel history gap", detail: "First-time applicants or those with no developed-country visa history face higher rejection rates." },
          { pct: 21, reason: "Previous UK refusal not declared", detail: "Must declare all prior UK refusals. Non-declaration is misrepresentation — grounds for 10-year ban." },
          { pct: 17, reason: "Applied too early or too late", detail: "Apply no earlier than 3 months before travel and no later than 3 weeks before (to allow processing)." },
        ],
        fixes: [
          { title: "Show 3–6 months of genuine savings", icon: "💰", impact: "High", desc: "Bank statements showing regular organic savings. Avoid lump-sum transfers in the 30 days before application. The Home Office checks for 'parking' funds." },
          { title: "Provide complete accommodation proof", icon: "🏠", impact: "High", desc: "Confirmed hotel bookings for entire stay, or host's invitation letter with full address, immigration status, and relationship to you." },
          { title: "Write a detailed cover letter", icon: "✍️", impact: "High", desc: "Explain every aspect of your trip: why UK, what you'll do, where you'll stay, who is funding it, and why you will definitely return home." },
          { title: "Include prior developed-country visas", icon: "✈️", impact: "Medium", desc: "Prior US, Canada, Schengen, or UAE visa significantly reduces 'travel history' concern. Include copies even if expired." },
          { title: "Apply online via UKVI portal", icon: "💻", impact: "Medium", desc: "Digital eVisa application via UKVI. Use the priority service (extra fee) if travel is within 3–4 weeks." },
          { title: "Declare all prior refusals honestly", icon: "📋", impact: "Critical", desc: "UK takes misrepresentation extremely seriously. Even a 'forgotten' refusal found in your record results in 10-year ban." },
        ],
        documents: [
          "Online UKVI application form",
          "Valid passport + all previous passports",
          "Biometrics at VFS Global",
          "Bank statements (3–6 months, all accounts)",
          "Employment letter (position, salary, leave dates)",
          "Payslips (3–6 months)",
          "Hotel bookings or host invitation letter",
          "Return flight itinerary",
          "Cover letter",
          "Proof of accommodation",
          "Travel history copies (previous visas, entry stamps)",
          "Income tax returns or P60 equivalent",
        ],
        stats: {
          approvalTime: "15–21 business days (standard), 5 days (priority)",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "UK eVisa is digital — no sticker in passport. You need a UKVI online account to prove your immigration status",
          "Priority service (£500+) gives decision within 5 business days — worth it for time-sensitive travel",
          "Apply no earlier than 3 months before travel — applications opened too early are sometimes refused",
          "If refused, you have a right of administrative review — not a full appeal. Hire a solicitor for complex cases",
          "Always book refundable hotels and flexible flights specifically for the visa application",
        ],
        successStories: "UK visitor visa applicants with stable employment, 3–6 months bank history, and clear travel purpose achieve approval rates of 71%.",
      },
      student: {
        rate: 14,
        risk: "Low",
        label: "UK Student Visa (Tier 4)",
        trend: "stable",
        trendNote: "UK student visa approvals strong following UKVI reforms",
        byNationality: { "Bangladesh": 16, "India": 11, "Pakistan": 18, "Nigeria": 22, "Average": 14 },
        topReasons: [
          { pct: 50, reason: "Financial requirements not met", detail: "Must show tuition + £1,015–£1,265/month living costs for course duration. Funds must be held for 28 consecutive days." },
          { pct: 38, reason: "CAS (Confirmation of Acceptance for Studies) issues", detail: "Expired or incorrect CAS, or inconsistency between CAS and application form." },
          { pct: 28, reason: "English language proof missing", detail: "Must meet B2 English level (IELTS 5.5–6.5 depending on institution). Official test results required." },
        ],
        fixes: [
          { title: "Hold funds for 28 consecutive days", icon: "💰", impact: "Critical", desc: "Bank balance must be clearly above the threshold for 28 days before application. Screenshot or official bank letter required." },
          { title: "Verify CAS is current and complete", icon: "📋", impact: "Critical", desc: "CAS expires. Check start date, institution details, and that all details match your application exactly." },
          { title: "IELTS score must meet institution requirement", icon: "📊", impact: "High", desc: "Check both the UKVI requirement AND your university's requirement. The higher threshold applies." },
        ],
        documents: [
          "CAS (Confirmation of Acceptance for Studies)",
          "ATAS certificate (if required for subject)",
          "Bank statements (28-day rule)",
          "English language test results",
          "Academic transcripts",
          "Tuberculosis test result (certain nationalities)",
          "Parental consent (if under 18)",
        ],
        stats: {
          approvalTime: "3 weeks",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: false,
        },
        tips: [
          "Apply no earlier than 6 months before course start",
          "Students from high-risk countries may receive a tuberculosis test requirement — check early",
        ],
        successStories: "UK student visa applicants meeting all financial and CAS requirements achieve 86%+ approval rates.",
      },
      work: {
        rate: 8,
        risk: "Low",
        label: "UK Skilled Worker Visa",
        trend: "down",
        trendNote: "Skilled Worker approvals high; NHS and tech sectors particularly strong",
        byNationality: { "Bangladesh": 10, "India": 7, "Pakistan": 11, "Nigeria": 12, "Average": 8 },
        topReasons: [
          { pct: 48, reason: "Salary below minimum threshold", detail: "Must meet the going rate for the SOC code AND the general threshold (£38,700 from April 2024)." },
          { pct: 35, reason: "CoS (Certificate of Sponsorship) issues", detail: "Sponsor licence issues or incorrect CoS details." },
          { pct: 25, reason: "English language requirement not met", detail: "B1 English required for Skilled Worker. Must be proven through approved test or exempt route." },
        ],
        fixes: [
          { title: "Verify salary meets new thresholds", icon: "💰", impact: "Critical", desc: "£38,700 general threshold from April 2024 (lower for shortage occupations). Confirm with your employer before applying." },
          { title: "Check sponsor licence is current", icon: "🏢", impact: "Critical", desc: "UK employers must hold a valid sponsor licence. Check the UKVI register before accepting a job offer." },
        ],
        documents: [
          "Certificate of Sponsorship (CoS) from employer",
          "English language evidence",
          "Tuberculosis test (certain nationalities)",
          "Maintenance funds proof (if below threshold)",
          "Qualifications certificates",
        ],
        stats: {
          approvalTime: "3–8 weeks",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Health and Care Worker visa offers lower fees and NHS surcharge exemption for eligible roles",
          "Shortage occupation roles have lower salary thresholds",
        ],
        successStories: "Skilled Worker visa applicants with compliant CoS and salary meeting thresholds achieve 92%+ approval rates.",
      },
      transit: {
        rate: 18,
        risk: "Medium",
        label: "Direct Airside Transit Visa (DATV)",
        trend: "stable",
        trendNote: "DATV required for specific nationalities even when not leaving the terminal",
        byNationality: { "Bangladesh": 22, "India": 8, "Pakistan": 25, "Nigeria": 30, "Average": 18 },
        topReasons: [
          { pct: 55, reason: "Applied too late", detail: "Apply at least 2–3 weeks before transit. Last-minute applications are often refused." },
          { pct: 38, reason: "Onward visa missing or invalid", detail: "Must show valid visa for destination country." },
          { pct: 25, reason: "Financial evidence missing", detail: "Even for transit, basic financial evidence is required." },
        ],
        fixes: [
          { title: "Apply 3 weeks before transit", icon: "📅", impact: "High", desc: "Standard processing is 15 business days. Never apply last-minute for DATV." },
          { title: "Show valid onward visa and tickets", icon: "✈️", impact: "Critical", desc: "Complete itinerary with confirmed onward booking and valid destination country visa." },
        ],
        documents: ["Valid passport", "Confirmed onward flight ticket", "Destination country visa", "UKVI application form"],
        stats: {
          approvalTime: "15 business days",
          biometricsRequired: false,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: false,
        },
        tips: [
          "DATV holders must remain in the international zone — no entry to UK",
          "Check if your nationality requires DATV — many countries are exempt",
        ],
        successStories: "DATV applications with complete itinerary and destination visa achieve 88%+ approval rates.",
      },
      business: {
        rate: 24,
        risk: "Medium",
        label: "UK Business Visitor Visa",
        trend: "stable",
        trendNote: "Business visitor visa uses same Standard Visitor route with additional business documents",
        byNationality: { "Bangladesh": 30, "India": 18, "Pakistan": 34, "Nigeria": 40, "Average": 24 },
        topReasons: [
          { pct: 58, reason: "Business activities not permitted under visitor rules", detail: "UK visitor visa does not permit work or employment. Permitted activities are specific — meetings, conferences, training." },
          { pct: 44, reason: "UK company invitation missing", detail: "No invitation letter from UK business contact or conference organizer." },
          { pct: 32, reason: "Financial evidence weak", detail: "Cannot show ability to fund UK trip costs." },
        ],
        fixes: [
          { title: "Get formal invitation from UK entity", icon: "📨", impact: "High", desc: "Invitation letter from UK company or conference organizer, on headed paper, with contact details and purpose." },
          { title: "Define permitted business activities clearly", icon: "📋", impact: "High", desc: "Attend meetings, negotiate deals, attend conferences. Do NOT claim you will be working for a UK company." },
        ],
        documents: ["UK company invitation letter", "Company registration and financial proof", "Conference registration", "Employment letter from home company", "Bank statements"],
        stats: {
          approvalTime: "15 business days (standard), 5 days (priority)",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Business visitor can also attend exhibitions, sign deals, and do short unpaid training",
          "If paid by UK entity, this becomes work — requires Skilled Worker visa",
        ],
        successStories: "Business visitor applications with formal UK invitations and strong employer backing achieve 76% approval rates.",
      },
      family: {
        rate: 31,
        risk: "High",
        label: "UK Family Visa / Spouse Visa",
        trend: "up",
        trendNote: "Family visa requirements tightened; income threshold raised to £29,000 in 2024",
        byNationality: { "Bangladesh": 36, "India": 25, "Pakistan": 40, "Nigeria": 45, "Average": 31 },
        topReasons: [
          { pct: 66, reason: "Financial requirement not met", detail: "UK sponsor must earn at least £29,000 (raised April 2024). Previous threshold was £18,600. Many applications caught by this change." },
          { pct: 52, reason: "Genuine relationship not proven", detail: "Home Office looks for evidence of cohabitation, joint finances, regular communication, and shared life plans." },
          { pct: 38, reason: "English language requirement", detail: "Applicants from most countries must pass A1 English (IELTS Life Skills or equivalent) to enter, A2 to extend." },
          { pct: 28, reason: "Suitability requirements", detail: "Criminal record, past immigration violations, or previous visa refusals affect suitability." },
        ],
        fixes: [
          { title: "Confirm sponsor meets £29,000 threshold", icon: "💰", impact: "Critical", desc: "P60, payslips, employment letter. Self-employed sponsors need SA302 returns. Threshold will rise further — check current requirement." },
          { title: "Take A1 English test if required", icon: "📊", impact: "Critical", desc: "Book IELTS Life Skills A1. Test must be from UKVI-approved centre. Results valid 2 years." },
          { title: "Document relationship extensively", icon: "📸", impact: "High", desc: "Joint bank accounts, bills, lease, photos over years, evidence of visits, communication logs." },
        ],
        documents: [
          "UK sponsor's payslips and P60",
          "Employment letter confirming salary",
          "Evidence of relationship (photos, communications, visits)",
          "English language test results (A1)",
          "Accommodation proof in UK",
          "Passport and travel history",
        ],
        stats: {
          approvalTime: "24 weeks (standard)",
          biometricsRequired: true,
          interviewRequired: false,
          onlineApply: true,
          appealAvailable: true,
        },
        tips: [
          "Income threshold will continue rising in 2025 — check current requirement before applying",
          "If sponsor cannot meet income requirement alone, savings over £16,000 can supplement",
        ],
        successStories: "UK spouse visa applicants meeting financial requirements with strong relationship evidence achieve 69% approval rates.",
      },
    },
  },
};

export const VISA_TYPE_LABELS = {
  tourist:  { label: "Tourist Visa",   icon: "✈️",  color: "bg-blue-100 text-blue-800 border-blue-200" },
  student:  { label: "Student Visa",   icon: "🎓",  color: "bg-purple-100 text-purple-800 border-purple-200" },
  work:     { label: "Work Visa",      icon: "💼",  color: "bg-green-100 text-green-800 border-green-200" },
  transit:  { label: "Transit Visa",   icon: "🔁",  color: "bg-cyan-100 text-cyan-800 border-cyan-200" },
  business: { label: "Business Visa",  icon: "🤝",  color: "bg-orange-100 text-orange-800 border-orange-200" },
  family:   { label: "Family Visa",    icon: "👨‍👩‍👧", color: "bg-pink-100 text-pink-800 border-pink-200" },
};

export const RISK_CONFIG = {
  Low:    { color: "text-green-700", bg: "bg-green-50",  border: "border-green-200",  bar: "bg-green-500" },
  Medium: { color: "text-amber-700", bg: "bg-amber-50",  border: "border-amber-200",  bar: "bg-amber-500" },
  High:   { color: "text-red-700",   bg: "bg-red-50",    border: "border-red-200",    bar: "bg-red-500" },
};

export const IMPACT_CONFIG = {
  Critical: { color: "text-red-700 bg-red-50 border-red-200" },
  High:     { color: "text-orange-700 bg-orange-50 border-orange-200" },
  Medium:   { color: "text-amber-700 bg-amber-50 border-amber-200" },
};

/**
 * ✅ FIXED: Exact slug-to-key matching
 * Tries exact match first, then partial, then falls back to generic.
 */
export function getRejectionData(destSlug) {
  // 1. Exact match
  if (REJECTION_RULES[destSlug]) {
    return { key: destSlug, ...REJECTION_RULES[destSlug] };
  }

  // 2. Partial match (slug contains a known key, e.g. "united-states-of-america" → "united-states")
  const partialKey = Object.keys(REJECTION_RULES).find(k => destSlug.includes(k));
  if (partialKey) {
    return { key: partialKey, ...REJECTION_RULES[partialKey] };
  }

  // 3. Generic fallback
  const destName = destSlug
    .split("-")
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return {
    key: "generic",
    name: destName,
    flag: "🌍",
    embassyUrl: null,
    types: {
      tourist:  { rate: 25, risk: "Medium", label: "Tourist / Visitor Visa", trend: "stable", trendNote: "Processing times vary by embassy", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
      student:  { rate: 18, risk: "Medium", label: "Student Visa",           trend: "stable", trendNote: "", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
      work:     { rate: 15, risk: "Low",    label: "Work Visa",              trend: "stable", trendNote: "", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
      transit:  { rate: 10, risk: "Low",    label: "Transit Visa",           trend: "stable", trendNote: "", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
      business: { rate: 20, risk: "Medium", label: "Business Visa",          trend: "stable", trendNote: "", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
      family:   { rate: 22, risk: "Medium", label: "Family Visa",            trend: "stable", trendNote: "", topReasons: [], fixes: [], documents: [], tips: [], stats: { approvalTime: "Varies", biometricsRequired: false, interviewRequired: false, onlineApply: false, appealAvailable: false } },
    },
  };
}